name: Deploy
on: [ workflow_dispatch ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          export DOCKER_CLIENT_TIMEOUT=120
          export COMPOSE_HTTP_TIMEOUT=120
          cd goodsreseller/
          docker-compose pull
          docker-compose up -d