name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
        
    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/goods-reseller:$(date +%s)
      
    - name: Docker Push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/goods-reseller
