name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-artifacts:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Backend
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/goods-reseller:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/goods-reseller:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/goods-reseller:buildcache,mode=max

    - name: Build and Push Migrator
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./migrator.dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/goods-reselle-migratorr:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/goods-reseller-migrator:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/goods-reseller-migrator:buildcache,mode=max

    - name: Build and Push Proxy
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./nginx.dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/goods-reselle-proxy:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/goods-reseller-proxy:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/goods-reseller-proxy:buildcache,mode=max
